from faker import Faker
import random
#recordame el poner la opcion de cambiar el idioma
fake = Faker ('es_MX')


#capacidades = lo que puede generar '0tematizzzdo'
# y el gato dijo miau

capacidades = {
    "nombre": fake.name,
    "email": fake.email,
    "telefono": fake.phone_number,
    "celular": fake.phone_number,
    "ciudad": fake.city,
    "pais": fake.country,
    "direccion": fake.address,
    "postal": fake.postcode,
    "postcode": fake.postcode,
    "ssn": fake.ssn,
    "username": fake.user_name,
    "usuario": fake.user_name,
    "compañia": fake.company,
    "empresa": fake.company,
    "trabajo": fake.job,
    "fecha": fake.date,
    "fecha_nacimiento": fake.date_of_birth,
    "color" : fake.color_name,
    "producto": fake.word,
    "lenguaje": fake.language_name,
    "idioma" : fake.language_name,
    "numero": lambda: random.randint(1, 10000),
    "tarjeta" : fake.credit_card_number,
    "precio" : lambda: round(random.uniform(10.0, 1000), 2),
    "salario" : lambda: random.randint(3000, 100000),
    "int": lambda: random.randint(1, 10000),
    "varchar": lambda: fake.word(),
    "descripcion" : lambda: fake.sentence(nb_words=6),
    "civil_estatus" : lambda: random.choice(["Soltero", "Casado", "Divorciado", "Viudo"]),
    "genero" : lambda: random.choice(["Masculino", "Femenino", "Otro"]),
    "boolean": lambda: random.choice([0, 1]),
    "id" :fake.uuid4(),
    "puesto" : fake.job,
    "empresa" : fake.company,
    "url" : fake.url,
    "ip" : fake.ipv4,
    "mac" : fake.mac_address,
    "estado" : fake.state,
    "estado_provincia" : fake.state,
    "region" : fake.state,
    "navegador" : fake.user_agent,
    "curp" : fake.curp,
    "rfc" : fake.rfc,
    "cvv" : fake.credit_card_security_code,
    "marca" : lambda: random.choice(["Toyota", "Ford", "Chevrolet", "Honda", "Nissan"]),
    "modelo" : lambda: random.choice(["Sedan", "SUV", "Hatchback", "Convertible", "Truck"]),
    "año" : lambda: random.randint(1990, 2023),
    "color_auto" : fake.color_name,
    "color_vehiculo" : fake.color_name,
    "curso" : lambda: random.choice(["Matemáticas", "Historia", "Ciencia", "Literatura", "Arte"]),
    "calificacion" : lambda: random.choice(["A", "B", "C", "D", "F"]),
    "nacionalidad" : fake.country,
    "religion" : lambda: random.choice(["Católica", "Protestante", "Musulmana", "Judía", "Hindú", "Budista", "Atea"]),
    "estado_civil" : lambda: random.choice(["Soltero", "Casado", "Divorciado", "Viudo"]),
    "hobby" : lambda: random.choice(["Leer", "Viajar", "Cocinar", "Deportes", "Música", "Jardinería"]),
    "aficion" : lambda: random.choice(["Leer", "Viajar", "Cocinar", "Deportes", "Música", "Jardinería"]),
    "mascota" : lambda: random.choice(["Perro", "Gato", "Pájaro", "Pez", "Hamster"]),
    "animal" : lambda: random.choice(["Perro", "Gato", "Pájaro", "Pez", "Hamster"]),
    "fruta" : lambda: random.choice(["Manzana", "Banana", "Naranja", "Uva", "Fresa"]),
    "verdura" : lambda: random.choice(["Lechuga", "Tomate", "Zanahoria", "Pepino", "Cebolla"]),
    "bebida" : lambda: random.choice(["Agua", "Jugo", "Refresco", "Café", "Té"]),
    "musica" : lambda: random.choice(["Rock", "Pop", "Jazz", "Clásica", "Hip-Hop"]),
    "deporte" : lambda: random.choice(["Fútbol", "Baloncesto", "Tenis", "Natación", "Ciclismo"]),
    "marca_ropa" : lambda: random.choice(["Nike", "Adidas", "Puma", "Reebok", "Under Armour"]),
    "talla_ropa" : lambda: random.choice(["S", "M", "L", "XL", "XXL"]),
    "tipo_sangre" : lambda: random.choice(["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"]),
    "alergia" : lambda: random.choice(["Polen", "Polvo", "Pelos de animales", "Alimentos", "Medicamentos"]),
    "medicamento" : lambda: random.choice(["Paracetamol", "Ibuprofeno", "Amoxicilina", "Loratadina", "Omeprazol"]),
    "enfermedad" : lambda: random.choice(["Diabetes", "Hipertensión", "Asma", "Alergias", "Artritis"]), 
    "hospital" : fake.company,
    "clinica" : fake.company,
    "universidad" : fake.company,
    "escuela" : fake.company,
    "instituto" : fake.company,
    "titulo" : lambda: random.choice(["Licenciatura", "Maestría", "Doctorado", "Diplomado", "Certificación"]),
    "grado" : lambda: random.choice(["Licenciatura", "Maestría", "Doctorado", "Diplomado", "Certificación"]),
    "idioma" : fake.language_name,
    "calle" : fake.street_name,
    "avenida" : fake.street_name,
    "barrio" : fake.city_suffix,
    "colonia" : fake.city_suffix,
    "municipio" : fake.city,
    "codigo_postal" : fake.postcode,
    "numero_ext" : lambda: str(random.randint(1, 9999)),
    "numero_int" : lambda: str(random.randint(1, 9999)),
    "referencia" : fake.sentence,
    "notas" : fake.text,
    "comentarios" : fake.text,
    "observaciones" : fake.text,
    "biografia" : fake.text,
    "correo_corporativo" : fake.company_email,
    "correo_personal" : fake.email,
    "pagina_web" : fake.url,
    "sitio_web" : fake.url,
    "red_social" : lambda: random.choice(["Facebook", "Twitter", "Instagram", "LinkedIn", "TikTok"]),
    "usuario_red" : fake.user_name,
    "contrasena" : fake.password,
    "password" : fake.password,
    "moneda" : lambda: random.choice(["USD", "EUR", "MXN", "GBP", "JPY"]),
    "cantidad" : lambda: round(random.uniform(1.0, 1000.0), 2),
    "precio" : lambda: round(random.uniform(10.0, 1000.0), 2),
    "descuento" : lambda: round(random.uniform(0.0, 100.0), 2),
    "total" : lambda: round(random.uniform(10.0, 10000.0), 2),
    "iva" : lambda: round(random.uniform(0.0, 100.0), 2),
    "subtotal" : lambda: round(random.uniform(10.0, 10000.0), 2),
    "factura" : fake.bothify(text='????-########'),
    "orden" : fake.bothify(text='ORD-########'),
    "pedido" : fake.bothify(text='PED-########'),
    "producto" : fake.word,
    "servicio" : fake.word,
    "categoria" : lambda: random.choice(["Electrónica", "Ropa", "Hogar", "Juguetes", "Libros"]),
    "marca_producto" : lambda: random.choice(["Sony", "Samsung", "Apple", "LG", "Dell"]),
    "modelo_producto" : lambda: random.choice(["X100", "ProMax", "Ultra", "S20", "Note"]),
    "color_producto" : fake.color_name,
    "talla_producto" : lambda: random.choice(["S", "M", "L", "XL", "XXL"]),
    "peso" : lambda: round(random.uniform(0.1, 100.0), 2),
    "altura" : lambda: round(random.uniform(0.1, 3.0), 2),
    "ancho" : lambda: round(random.uniform(0.1, 3.0), 2),
    "largo" : lambda: round(random.uniform(0.1, 3.0), 2),
    "volumen" : lambda: round(random.uniform(0.1, 100.0), 2),
    "capacidad" : lambda: round(random.uniform(1.0, 1000.0), 2),
    "stock" : lambda: random.randint(0, 1000),
    "inventario" : lambda: random.randint(0, 1000),
    "iban" : fake.iban,
    "swift" : fake.swift,
    "ipv6" : fake.ipv6,
    "Metodo_pago" : lambda: random.choice(["Efectivo", "Tarjeta de crédito", "Tarjeta de débito", "Transferencia bancaria", "PayPal"]),
    "estatus" : lambda: random.choice(["Activo", "Inactivo", "Pendiente", "Completado", "Cancelado"]),
    "estado_pedido" : lambda: random.choice(["Activo", "Inactivo", "Pendiente", "Completado", "Cancelado"]),
    "prioridad" : lambda: random.choice(["Baja", "Media", "Alta"]),
    "nivel" : lambda: random.choice(["Básico", "Intermedio", "Avanzado"]),
    "placa_auto" : fake.license_plate,
    "placa_vehiculo" : fake.license_plate,
    "motor" : lambda: random.choice(["V6", "V8", "I4", "Electric", "Hybrid"]),
    "pais_origen" : fake.country,
    "pais_destino" : fake.country,
    "puerto" : fake.city,
    "aeropuerto" : fake.city,
    "terminal" : fake.city,
    "vuelo" : fake.bothify(text='??####'),
    "asiento" : fake.bothify(text='?#'),
    "clase" : lambda: random.choice(["Económica", "Business", "Primera"]),
    "hotel": lambda: fake.company() + " Hotel",
    "habitacion": lambda: random.randint(100, 999),
    "noches" : lambda: random.randint(1,30),
    "pasaporte" : fake.bothify(text='??######'),
    "visa" : fake.bothify(text='##########'),
    "licencia" : fake.bothify(text='##########'),
    "certificado" : fake.bothify(text='##########'),
    "numero_seguridad_social" : fake.ssn,
    "numero_seguro_social" : fake.ssn,
    "afiliacion" : fake.bothify(text='##########'),
    "peso_kg" : lambda: round(random.uniform(30.0, 200.0), 2),
    "altura_cm" : lambda: round(random.uniform(100.0, 250.0), 2),
    "imc" : lambda: round(random.uniform(15.0, 40.0), 2),
    "frecuencia_cardiaca" : lambda: random.randint(60, 100),
    "presion_arterial" : lambda: f"{random.randint(90, 140)}/{random.randint(60, 90)}",
    "temperatura" : lambda: round(random.uniform(36.0, 39.0), 1),
    "oxigenacion" : lambda: random.randint(90, 100),
    "glucosa" : lambda: random.randint(70, 140),
    "colesterol" : lambda: random.randint(150, 250),
    "trigliceridos" : lambda: random.randint(50, 200),
    "juego" : fake.word() + " Game",
    "consola" : lambda: random.choice(["PlayStation", "Xbox", "Nintendo Switch", "PC"]),
    "plataforma_juego" : lambda: random.choice(["Steam", "Epic Games", "Origin", "Uplay"]),
    "genero_juego" : lambda: random.choice(["Acción", "Aventura", "RPG", "Estrategia", "Deportes"]),
    "nickname" : fake.user_name,
    "voltaje": lambda: random.randint(1, 480),
    "gamer_tag" : fake.user_name,
    "voltaje" : lambda: random.randint(1,1000)
    #si vas a seguir agregando recuerda que tambien debes poner , la coma "," esta coma
    # la que esta al lado del . este "." el punto poes
    }