from faker import Faker
import random
#recordame el poner la opcion de cambiar el idioma
fake = Faker ('es_MX')

#capacidades = lo que puede generar '0tematizzzdo'
# y el gato dijo miau
# chingaderes al azar bamos 💋

from faker import Faker
import random

capacidades = {
    # === Personales básicas ===
    "nombre": fake.name,
    "email": fake.email,
    "telefono": fake.phone_number,
    "celular": fake.phone_number,
    "ciudad": fake.city,
    "pais": fake.country,
    "direccion": fake.address,
    "postal": fake.postcode,
    "postcode": fake.postcode,
    "ssn": fake.ssn,
    "username": fake.user_name,
    "usuario": fake.user_name,
    "compañia": fake.company,
    "empresa": fake.company,
    "trabajo": fake.job,
    "fecha": fake.date,
    "fecha_nacimiento": fake.date_of_birth,
    "color": fake.color_name,
    "lenguaje": fake.language_name,
    "idioma": fake.language_name,
    "numero": lambda: random.randint(1, 10000),
    "tarjeta": fake.credit_card_number,
    "precio": lambda: round(random.uniform(10.0, 1000.0), 2),
    "salario": lambda: random.randint(3000, 100000),
    "int": lambda: random.randint(1, 10000),
    "varchar": lambda: fake.word(),
    "descripcion": lambda: fake.sentence(nb_words=6),
    "civil_estatus": lambda: random.choice(["Soltero", "Casado", "Divorciado", "Viudo"]),
    "genero": lambda: random.choice(["Masculino", "Femenino", "Otro"]),
    "boolean": lambda: random.choice([0, 1]),
    "id": fake.uuid4,
    "puesto": fake.job,
    "url": fake.url,
    "ip": fake.ipv4,
    "mac": fake.mac_address,
    "estado": fake.state,
    "estado_provincia": fake.state,
    "region": fake.state,
    "navegador": fake.user_agent,
    "curp": fake.curp,
    "rfc": fake.rfc,
    "cvv": fake.credit_card_security_code,
    "marca": lambda: random.choice(["Toyota", "Ford", "Chevrolet", "Honda", "Nissan"]),
    "modelo": lambda: random.choice(["Sedan", "SUV", "Hatchback", "Convertible", "Truck"]),
    "año": lambda: random.randint(1990, 2023),
    "color_auto": fake.color_name,
    "color_vehiculo": fake.color_name,
    "curso": lambda: random.choice(["Matemáticas", "Historia", "Ciencia", "Literatura", "Arte"]),
    "calificacion": lambda: random.choice(["A", "B", "C", "D", "F"]),
    "nacionalidad": fake.country,
    "religion": lambda: random.choice(["Católica", "Protestante", "Musulmana", "Judía", "Hindú", "Budista", "Atea"]),
    "hobby": lambda: random.choice(["Leer", "Viajar", "Cocinar", "Deportes", "Música", "Jardinería"]),
    "aficion": lambda: random.choice(["Leer", "Viajar", "Cocinar", "Deportes", "Música", "Jardinería"]),
    "mascota": lambda: random.choice(["Perro", "Gato", "Pájaro", "Pez", "Hamster"]),
    "animal": lambda: random.choice(["Perro", "Gato", "Pájaro", "Pez", "Hamster"]),
    "fruta": lambda: random.choice(["Manzana", "Banana", "Naranja", "Uva", "Fresa"]),
    "verdura": lambda: random.choice(["Lechuga", "Tomate", "Zanahoria", "Pepino", "Cebolla"]),
    "bebida": lambda: random.choice(["Agua", "Jugo", "Refresco", "Café", "Té"]),
    "musica": lambda: random.choice(["Rock", "Pop", "Jazz", "Clásica", "Hip-Hop"]),
    "deporte": lambda: random.choice(["Fútbol", "Baloncesto", "Tenis", "Natación", "Ciclismo"]),
    "marca_ropa": lambda: random.choice(["Nike", "Adidas", "Puma", "Reebok", "Under Armour"]),
    "talla_ropa": lambda: random.choice(["S", "M", "L", "XL", "XXL"]),
    "tipo_sangre": lambda: random.choice(["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"]),
    "alergia": lambda: random.choice(["Polen", "Polvo", "Pelos de animales", "Alimentos", "Medicamentos"]),
    "medicamento": lambda: random.choice(["Paracetamol", "Ibuprofeno", "Amoxicilina", "Loratadina", "Omeprazol"]),
    "enfermedad": lambda: random.choice(["Diabetes", "Hipertensión", "Asma", "Alergias", "Artritis"]),
    "hospital": fake.company,
    "clinica": fake.company,
    "universidad": fake.company,
    "escuela": fake.company,
    "instituto": fake.company,
    "titulo": lambda: random.choice(["Licenciatura", "Maestría", "Doctorado", "Diplomado", "Certificación"]),
    "grado": lambda: random.choice(["Licenciatura", "Maestría", "Doctorado", "Diplomado", "Certificación"]),
    "calle": fake.street_name,
    "avenida": fake.street_name,
    "barrio": fake.city_suffix,
    "colonia": fake.city_suffix,
    "municipio": fake.city,
    "codigo_postal": fake.postcode,
    "numero_ext": lambda: str(random.randint(1, 9999)),
    "numero_int": lambda: str(random.randint(1, 9999)),
    "referencia": fake.sentence,
    "notas": fake.text,
    "comentarios": fake.text,
    "observaciones": fake.text,
    "biografia": fake.text,
    "correo_corporativo": fake.company_email,
    "correo_personal": fake.email,
    "pagina_web": fake.url,
    "sitio_web": fake.url,
    "red_social": lambda: random.choice(["Facebook", "Twitter", "Instagram", "LinkedIn", "TikTok"]),
    "usuario_red": fake.user_name,
    "contrasena": fake.password,
    "password": fake.password,
    "moneda": lambda: random.choice(["USD", "EUR", "MXN", "GBP", "JPY"]),
    "cantidad": lambda: round(random.uniform(1.0, 1000.0), 2),
    "descuento": lambda: round(random.uniform(0.0, 100.0), 2),
    "total": lambda: round(random.uniform(10.0, 10000.0), 2),
    "iva": lambda: round(random.uniform(0.0, 100.0), 2),
    "subtotal": lambda: round(random.uniform(10.0, 10000.0), 2),
    "factura": fake.bothify(text='????-########'),
    "orden": fake.bothify(text='ORD-########'),
    "pedido": fake.bothify(text='PED-########'),
    "servicio": fake.word,
    "categoria": lambda: random.choice(["Electrónica", "Ropa", "Hogar", "Juguetes", "Libros"]),
    "marca_producto": lambda: random.choice(["Sony", "Samsung", "Apple", "LG", "Dell"]),
    "modelo_producto": lambda: random.choice(["X100", "ProMax", "Ultra", "S20", "Note"]),
    "color_producto": fake.color_name,
    "talla_producto": lambda: random.choice(["S", "M", "L", "XL", "XXL"]),
    "peso": lambda: round(random.uniform(0.1, 100.0), 2),
    "altura": lambda: round(random.uniform(0.1, 3.0), 2),
    "ancho": lambda: round(random.uniform(0.1, 3.0), 2),
    "largo": lambda: round(random.uniform(0.1, 3.0), 2),
    "volumen": lambda: round(random.uniform(0.1, 100.0), 2),
    "capacidad": lambda: round(random.uniform(1.0, 1000.0), 2),
    "stock": lambda: random.randint(0, 1000),
    "inventario": lambda: random.randint(0, 1000),
    "iban": fake.iban,
    "curp": fake.curp,
    "swift": fake.swift,
    "ipv6": fake.ipv6,
    "Metodo_pago": lambda: random.choice(["Efectivo", "Tarjeta de crédito", "Tarjeta de débito", "Transferencia bancaria", "PayPal"]),
    "estatus": lambda: random.choice(["Activo", "Inactivo", "Pendiente", "Completado", "Cancelado"]),
    "estado_pedido": lambda: random.choice(["Activo", "Inactivo", "Pendiente", "Completado", "Cancelado"]),
    "prioridad": lambda: random.choice(["Baja", "Media", "Alta"]),
    "nivel": lambda: random.choice(["Básico", "Intermedio", "Avanzado"]),
    "placa_auto": fake.license_plate,
    "placa_vehiculo": fake.license_plate,
    "motor": lambda: random.choice(["V6", "V8", "I4", "Electric", "Hybrid"]),
    "pais_origen": fake.country,
    "pais_destino": fake.country,
    "puerto": fake.city,
    "aeropuerto": fake.city,
    "terminal": fake.city,
    "vuelo": fake.bothify(text='??####'),
    "asiento": fake.bothify(text='?#'),
    "clase": lambda: random.choice(["Económica", "Business", "Primera"]),
    "hotel": lambda: fake.company() + " Hotel",
    "habitacion": lambda: random.randint(100, 999),
    "noches": lambda: random.randint(1, 30),
    "pasaporte": fake.bothify(text='??######'),
    "visa": fake.bothify(text='##########'),
    "licencia": fake.bothify(text='##########'),
    "certificado": fake.bothify(text='##########'),
    "numero_seguridad_social": fake.ssn,
    "afiliacion": fake.bothify(text='##########'),
    "peso_kg": lambda: round(random.uniform(30.0, 200.0), 2),
    "altura_cm": lambda: round(random.uniform(100.0, 250.0), 2),
    "imc": lambda: round(random.uniform(15.0, 40.0), 2),
    "frecuencia_cardiaca": lambda: random.randint(60, 100),
    "presion_arterial": lambda: f"{random.randint(90, 140)}/{random.randint(60, 90)}",
    "temperatura": lambda: round(random.uniform(36.0, 39.0), 1),
    "oxigenacion": lambda: random.randint(90, 100),
    "glucosa": lambda: random.randint(70, 140),
    "colesterol": lambda: random.randint(150, 250),
    "trigliceridos": lambda: random.randint(50, 200),
    "juego": lambda: fake.word() + " Game",
    "consola": lambda: random.choice(["PlayStation", "Xbox", "Nintendo Switch", "PC"]),
    "plataforma_juego": lambda: random.choice(["Steam", "Epic Games", "Origin", "Uplay"]),
    "genero_juego": lambda: random.choice(["Acción", "Aventura", "RPG", "Estrategia", "Deportes"]),
    "nickname": fake.user_name,
    "gamer_tag": fake.user_name,
    "voltaje": lambda: random.randint(1, 1000),

    # ========== NUEVAS ENTRADAS (más de 150) ==========
    # === Finanzas y negocios ===
    "cuenta_bancaria": fake.bban,
    "clabe": lambda: ''.join([str(random.randint(0,9)) for _ in range(18)]),
    "saldo": lambda: round(random.uniform(0.0, 100000.0), 2),
    "interes": lambda: round(random.uniform(0.1, 20.0), 2),
    "plazo": lambda: random.randint(1, 360),
    "comision": lambda: round(random.uniform(0.0, 100.0), 2),
    "inversion": lambda: round(random.uniform(1000.0, 500000.0), 2),
    "rentabilidad": lambda: round(random.uniform(-10.0, 30.0), 2),
    "accion": lambda: random.choice(["AAPL", "GOOGL", "MSFT", "AMZN", "TSLA"]),
    "dividendo": lambda: round(random.uniform(0.0, 5.0), 2),
    "cotizacion": lambda: round(random.uniform(10.0, 2000.0), 2),

    # === Vehículos (más detalle) ===
    "chasis": fake.bothify(text='????????????????'),
    "vin": fake.bothify(text='?????????????????????????'),
    "tipo_vehiculo": lambda: random.choice(["Automóvil", "Camioneta", "Motocicleta", "Camión", "Autobús"]),
    "cilindraje": lambda: random.choice([1.0, 1.4, 1.6, 2.0, 2.5, 3.0, 4.0]),
    "transmision": lambda: random.choice(["Manual", "Automática", "CVT", "DCT"]),
    "combustible": lambda: random.choice(["Gasolina", "Diésel", "Eléctrico", "Híbrido", "Etanol"]),
    "neumatico": lambda: random.choice(["Michelin", "Bridgestone", "Goodyear", "Continental", "Pirelli"]),
    "seguro_auto": lambda: random.choice(["GNP", "Qualitas", "AXA", "BBVA", "Mapfre"]),

    # === Tecnología y dispositivos ===
    "so": lambda: random.choice(["Windows", "macOS", "Linux", "Android", "iOS"]),
    "version_so": lambda: random.choice(["10", "11", "Ventura", "Sonoma", "Ubuntu 22.04"]),
    "ram_gb": lambda: random.choice([4, 8, 16, 32, 64]),
    "almacenamiento_gb": lambda: random.choice([128, 256, 512, 1024, 2048]),
    "procesador": lambda: random.choice(["Intel i3", "Intel i5", "Intel i7", "Ryzen 5", "Ryzen 7", "M1", "M2"]),
    "resolucion": lambda: random.choice(["1920x1080", "2560x1440", "3840x2160", "1366x768"]),
    "frecuencia_hz": lambda: random.choice([60, 120, 144, 240]),
    "bateria_mah": lambda: random.randint(2000, 6000),
    "conectividad": lambda: random.choice(["WiFi", "Bluetooth", "Ethernet", "5G", "4G"]),
    "navegador_web": lambda: random.choice(["Chrome", "Firefox", "Edge", "Safari", "Opera"]),
    "extension_archivo": lambda: random.choice([".txt", ".pdf", ".docx", ".jpg", ".png", ".mp4"]),

    # === Salud y medicina ===
    "diagnostico": lambda: random.choice(["Resfriado común", "Gripe", "COVID-19", "Fractura", "Infección estomacal"]),
    "tratamiento": lambda: random.choice(["Reposo", "Medicamentos", "Cirugía", "Fisioterapia", "Dieta"]),
    "medico": fake.name,
    "especialidad": lambda: random.choice(["Cardiología", "Pediatría", "Neurología", "Dermatología", "Ginecología"]),
    "cita_fecha": fake.future_date,
    "costo_consulta": lambda: random.randint(300, 2000),
    "seguro_medico": lambda: random.choice(["IMSS", "ISSSTE", "Seguro Popular", "GNP Seguros", "AXA"]),
    "alergeno": lambda: random.choice(["Ninguno", "Penicilina", "Mariscos", "Frutos secos", "Látex"]),
    "vacuna": lambda: random.choice(["COVID-19", "Influenza", "Hepatitis B", "VPH", "Tétanos"]),
    "dosis": lambda: random.randint(1, 3),

    # === Educación y cursos ===
    "materia": lambda: random.choice(["Matemáticas", "Física", "Química", "Biología", "Historia", "Inglés"]),
    "profesor": fake.name,
    "salon": lambda: random.choice(["A101", "B202", "C303", "Lab1", "Auditorio"]),
    "creditos": lambda: random.randint(3, 12),
    "semestre": lambda: random.randint(1, 12),
    "promedio": lambda: round(random.uniform(5.0, 10.0), 1),
    "beca": lambda: random.choice(["Ninguna", "Deportiva", "Académica", "Económica", "Excelencia"]),
    "examen": lambda: random.choice(["Parcial 1", "Parcial 2", "Final", "Extraordinario", "Titulación"]),
    "puntuacion": lambda: random.randint(0, 100),

    # === Comida y bebidas (más variedad) ===
    "platillo": lambda: random.choice(["Tacos", "Enchiladas", "Pizza", "Hamburguesa", "Sushi", "Ceviche"]),
    "postre": lambda: random.choice(["Pastel", "Helado", "Flan", "Gelatina", "Brownie"]),
    "sabor": lambda: random.choice(["Dulce", "Salado", "Ácido", "Amargo", "Umami"]),
    "receta": fake.sentence,
    "chef": fake.name,
    "restaurante": fake.company,
    "calorias": lambda: random.randint(100, 1500),
    "alimento": lambda: random.choice(["Pan", "Leche", "Huevo", "Pollo", "Pescado", "Carne"]),

    # === Deportes y fitness ===
    "equipo_deporte": lambda: random.choice(["Real Madrid", "Barcelona", "Lakers", "Celtics", "Yankees"]),
    "posicion": lambda: random.choice(["Delantero", "Defensa", "Medio", "Portero", "Base", "Ala"]),
    "entrenador": fake.name,
    "estadio": fake.city,
    "torneo": lambda: random.choice(["Mundial", "Liga MX", "NBA", "Super Bowl", "Champions"]),
    "récord": lambda: random.choice(["Goles", "Puntos", "Tiempo", "Distancia", "Velocidad"]),
    "lesion": lambda: random.choice(["Esguince", "Fractura", "Desgarro", "Tendinitis", "Conmoción"]),

    # === Viajes y turismo ===
    "aerolinea": lambda: random.choice(["Aeroméxico", "Volaris", "Delta", "American", "United"]),
    "destino": fake.city,
    "origen": fake.city,
    "escala": fake.city,
    "maleta_kg": lambda: random.randint(5, 30),
    "tour": lambda: random.choice(["City tour", "Playa", "Montaña", "Cultural", "Aventura"]),
    "guia": fake.name,
    "hotel_estrellas": lambda: random.choice([1, 2, 3, 4, 5]),
    "reserva": fake.bothify(text='RES-######'),

    # === Música y entretenimiento ===
    "artista": fake.name,
    "album": fake.word().capitalize(),
    "cancion": fake.sentence(nb_words=3),
    "genero_musical": lambda: random.choice(["Rock", "Pop", "Reggaetón", "Electrónica", "Banda", "Clásica"]),
    "premio": lambda: random.choice(["Grammy", "Oscar", "MTV", "Latin Grammy", "Billboard"]),
    "pelicula": fake.sentence(nb_words=2),
    "director": fake.name,
    "actor": fake.name,
    "serie": fake.word().capitalize(),
    "plataforma_streaming": lambda: random.choice(["Netflix", "Amazon Prime", "Disney+", "HBO Max", "Spotify"]),

    # === Videojuegos (más) ===
    "personaje": fake.first_name,
    "nivel_juego": lambda: random.randint(1, 100),
    "puntaje": lambda: random.randint(0, 9999),
    "logro": lambda: random.choice(["Completado", "Experto", "Velocidad", "Coleccionista", "Leyenda"]),
    "gremio": fake.word(),
    "servidor": fake.word(),
    "moneda_juego": lambda: random.choice(["Oro", "Plata", "Diamantes", "Puntos", "Tokens"]),

    # === Medio ambiente y geografía ===
    "clima": lambda: random.choice(["Soleado", "Lluvioso", "Nublado", "Nevado", "Ventoso"]),
    "temperatura_celsius": lambda: random.randint(-10, 45),
    "humedad": lambda: random.randint(20, 100),
    "presion_atmosferica": lambda: random.randint(980, 1050),
    "viento_kmh": lambda: random.randint(0, 120),
    "rio": fake.city,
    "montana": fake.city,
    "lago": fake.city,
    "continente": lambda: random.choice(["América", "Europa", "Asia", "África", "Oceanía", "Antártida"]),

    # === Ciencia y tecnología ===
    "elemento_quimico": lambda: random.choice(["H", "He", "C", "O", "Fe", "Au", "Ag"]),
    "compuesto": lambda: random.choice(["Agua", "Sal", "Azúcar", "Etanol", "Metano"]),
    "laboratorio": fake.company,
    "investigador": fake.name,
    "descubrimiento": fake.sentence,
    "patente": fake.bothify(text='PAT-######'),
    "robot": fake.word().capitalize() + "Bot",
    "algoritmo": lambda: random.choice(["Árbol de decisión", "Red neuronal", "K-means", "Regresión lineal", "SVM"]),

    # === Misceláneo (desmadre final) ===
    "chiste": lambda: random.choice(["¿Qué le dice un techo a otro? Techo de menos.", "¿Por qué el libro de matemáticas estaba triste? Porque tenía muchos problemas."]),
    "insulto_ligero": lambda: random.choice(["tonto", "bobalicón", "cabeza hueca", "patán", "zoquete"]),
    "frase_motivacional": lambda: random.choice(["Échale ganas", "Hoy puede ser un gran día", "Sin miedo al éxito", "A darle átomos"]),
    "emoji": lambda: random.choice(["😀", "😂", "❤️", "🔥", "💩", "🐍", "🍕"]),
    "color_hex": lambda: "#" + ''.join([random.choice('0123456789ABCDEF') for _ in range(6)]),
    "latitud": lambda: round(random.uniform(-90, 90), 6),
    "longitud": lambda: round(random.uniform(-180, 180), 6),
    "fecha_hora": fake.date_time,
    "timestamp": lambda: int(random.random() * 1e9),
    "token": fake.md5,
    "hash": fake.sha1,
    "qr": fake.bothify(text='QR-####-####-####'),
    # ¡Y hasta aquí por hoy, pero si falta desmadre, le seguimos!
}
    #si vas a seguir agregando recuerda que tambien debes poner , la coma "," esta coma
    # la que esta al lado del . este "." el punto poes
